version: "3"
services:
  web:
    restart: always
    build: 
      context: ./Ecoupon-client/
      dockerfile: Dockerfile.developement
    ports: 
      - 4200:4200 
    volumes: 
      - /ecoupon/client/node_modules
      - ./Ecoupon-client:/ecoupon/client
  api:
    restart: always
    build:
      context: ./ecoupon-backend/
      dockerfile: Dockerfile.developement
    ports:
      - 5000:5000
    volumes:
      - ./ecoupon-backend/:/ecoupon/api
    depends_on: 
      - database
  database:
    restart: always
    build: 
      context: ./ecoupon-database/    
      dockerfile: Dockerfile.developement