FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /ecoupon/api
COPY . .
RUN dotnet restore
RUN dotnet build
CMD [ "dotnet", "watch","--project","ecoupon.api/ecoupon.api.csproj","run"," --urls","http://0.0.0.0:5000"]