FROM postgres
WORKDIR /ecoupon/database
COPY . .
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_PORT=5432
USER postgres
# COPY *.sh /docker-entrypoint-initdb.d
# RUN initdb
# RUN pg_lsclusters
# RUN /etc/init.d/postgresql start
# RUN service postgresql start
# 
# RUN /bin/bash -c "init-db.sh"
# RUN bash init-db.sh
# RUN echo "host all all all $POSTGRES_HOST_AUTH_METHOD" >> pg_hba.conf